from enum import StrEnum


class AttemptOutcome(StrEnum):
    SOLVED_INDEPENDENTLY = "SOLVED_INDEPENDENTLY"
    SOLVED_SMALL_HINT = "SOLVED_SMALL_HINT"
    SOLVED_SIGNIFICANT_HELP = "SOLVED_SIGNIFICANT_HELP"
    UNDERSTOOD_AFTER_SOLUTION = "UNDERSTOOD_AFTER_SOLUTION"
    FAILED = "FAILED"
    SKIPPED = "SKIPPED"


class HintUsage(StrEnum):
    NONE = "NONE"
    SMALL = "SMALL"
    SIGNIFICANT = "SIGNIFICANT"
    SOLUTION_VIEWED = "SOLUTION_VIEWED"
    NOT_APPLICABLE = "NOT_APPLICABLE"
